apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ .Release.Name }}-configmap
  namespace: monitoring
  labels: 
    {{- include "pg-chart.labels" . | nindent 4 }}
data: 
  {{ .Values.config.name }}: |
    {{- toJson .Values.config.data | nindent 4 }}
