apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: {{ .Release.Name }}-pvc
  namespace: monitoring
  labels: 
    {{- include "pg-chart.labels" . | nindent 4 }}
spec: 
  accessModes: 
    - {{ .Values.pvc.accessMode }}
  resources: 
    requests: 
      storage: {{ .Values.pvc.storageSize }}
  storageClassName: {{ .Values.pvc.storageClassName }}

